SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

IF OBJECT_ID('tempdb..#TransactionGLID') IS NOT NULL DROP TABLE #TransactionGLID
CREATE TABLE #TransactionGLID ( GLID BIGINT )
INSERT INTO #TransactionGLID (GLID)
SELECT GLID FROM Transactions WHERE FK_CustomerID = 2014041501

DECLARE @RowsLeft INT = (SELECT COUNT(*) FROM #TransactionGLID)
WHILE(@RowsLeft > 0)
BEGIN
	UPDATE Transactions
	SET Commission2 = Commission3, Commission3 = Commission2
	WHERE GLID IN (SELECT TOP 1000 GLID FROM #TransactionGLID ORDER BY GLID)

	DELETE #TransactionGLID WHERE GLID IN (SELECT TOP 1000 GLID FROM #TransactionGLID ORDER BY GLID)

	SET @RowsLeft -= @@ROWCOUNT
END